/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned long vuint32_t;
typedef unsigned long          uint32_t;

#define GPIO_PortA_BASE_ADD 0x40010800
#define RCC_BASE_ADD        0x40021000
#define RCC_APB2ENR         *(vuint32_t *)(RCC_BASE_ADD        + 0x18)
#define GPIO_PortA_CRH      *(vuint32_t *)(GPIO_PortA_BASE_ADD + 0x04)
#define GPIO_PortA_ODR      *(vuint32_t *)(GPIO_PortA_BASE_ADD + 0x0C)

typedef union{
	vuint32_t All_Pins;
	struct{
		vuint32_t Pin_0:1 ;
		vuint32_t Pin_1:1 ;
		vuint32_t Pin_2:1 ;
		vuint32_t Pin_3:1 ;
		vuint32_t Pin_4:1 ;
		vuint32_t Pin_5:1 ;
		vuint32_t Pin_6:1 ;
		vuint32_t Pin_7:1 ;
		vuint32_t Pin_8:1 ;
		vuint32_t Pin_9:1 ;
		vuint32_t Pin_10:1 ;
		vuint32_t Pin_11:1 ;
		vuint32_t Pin_12:1 ;
		vuint32_t Pin_13:1 ;
		vuint32_t Pin_14:1 ;
		vuint32_t Pin_15:1 ;
	}Pins;
}U_ODRreg_t;

volatile U_ODRreg_t* ODRReg_PortA = (volatile U_ODRreg_t*)(GPIO_PortA_BASE_ADD + 0x0C);

int main(void)
{
	/* 1st : Set IOPAEN bit, bit 2, in APB2ENR register */
	RCC_APB2ENR |= (1<<2);
	/* 2nd : Set bits 5, 6, 7, 8 in CRH register to 2   */
	GPIO_PortA_CRH &= 0xFF0FFFFF;
	GPIO_PortA_CRH |= 0x00200000;
    /* Loop forever */
	while(1)
	{
		ODRReg_PortA->Pins.Pin_13=0;
		for(int i=0; i<5000; i++);
		ODRReg_PortA->Pins.Pin_13=1;
		for(int i=0; i<5000; i++);
	}//end for loop
}//end main
