/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned long vuint32_t;
typedef unsigned long          uint32_t;

#define GPIO_PortA_BASE_ADD 0x40010800
#define RCC_BASE_ADD        0x40021000
#define RCC_APB2ENR         *(vuint32_t *)(RCC_BASE_ADD        + 0x18)
#define GPIO_PortA_CRH      *(vuint32_t *)(GPIO_PortA_BASE_ADD + 0x04)
#define GPIO_PortA_ODR      *(vuint32_t *)(GPIO_PortA_BASE_ADD + 0x0C)

typedef union{
	vuint32_t All_Bits;
	struct{
		vuint32_t Bit0:1;
		vuint32_t Bit1:1;
		vuint32_t Bit2:1;
		vuint32_t Bit3:1;
		vuint32_t Bit4:1;
		vuint32_t Bit5:1;
		vuint32_t Bit6:1;
		vuint32_t Bit7:1;
		vuint32_t Bit8:1;
		vuint32_t Bit9:1;
		vuint32_t Bit10:1;
		vuint32_t Bit11:1;
		vuint32_t Bit12:1;
		vuint32_t Bit13:1;
		vuint32_t Bit14:1;
		vuint32_t Bit15:1;
	}Bits;
}U32BitsReg_t;

volatile U32BitsReg_t* AODR_Reg    = (volatile U32BitsReg_t*)(GPIO_PortA_BASE_ADD + 0x0C); /*.data section*/

volatile unsigned char init_g_variables[3]={1,2,3};/*.data section*/
volatile unsigned char uninit_g_variables;/*.bss section*/
volatile unsigned char const const_variables[3]={1,2,3};/*.rodata section*/

int main(void)
{
	int j, i;
	/* 1st : Set IOPAEN bit, bit 2, in APB2ENR register */
	RCC_APB2ENR |= (1<<2);
	/* 2nd : Set bits 5, 6, 7, 8 in CRH register to 2   */
	GPIO_PortA_CRH &= 0xFF0FFFFF;
	GPIO_PortA_CRH |= 0x00200000;
    /* Loop forever */
	while(1)
	{
		AODR_Reg->Bits.Bit13=1;
		for( i=0; i<5000; i++);
		AODR_Reg->Bits.Bit13=0;
		for( j=0; j<5000; j++);
	}//end for loop
}//end main
